01/23/2025 17:23:24 - INFO - __main__ - ***** Running training *****
01/23/2025 17:23:24 - INFO - __main__ -   Num examples = 90092
01/23/2025 17:23:24 - INFO - __main__ -   Num batches each epoch = 704
01/23/2025 17:23:24 - INFO - __main__ -   Num Epochs = 114
01/23/2025 17:23:24 - INFO - __main__ -   Instantaneous batch size per device = 64
01/23/2025 17:23:24 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 128
01/23/2025 17:23:24 - INFO - __main__ -   Gradient Accumulation steps = 1
01/23/2025 17:23:24 - INFO - __main__ -   Total optimization steps = 80000
01/23/2025 17:23:24 - INFO - __main__ -  do_classifier_free_guidance = True
01/23/2025 17:23:24 - INFO - __main__ -  conditioning_dropout_prob = 0.05
Checkpoint 'latest' does not exist. Starting a new training run.
Steps:   0%|                                                                                                                                                                      | 0/80000 [00:00<?, ?it/s]/share/phoenix/nfs02/S6/localdisk/hj453/.conda/envs/neural-gaffer/lib/python3.9/site-packages/torch/utils/checkpoint.py:1399: FutureWarning: `torch.cpu.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cpu', args...)` instead.
  with device_autocast_ctx, torch.cpu.amp.autocast(**cpu_autocast_kwargs), recompute_context:  # type: ignore[attr-defined]
Steps:   0%|                                                                                                                                                          | 1/80000 [00:09<211:03:48,  9.50s/it]01/23/2025 17:23:36 - INFO - __main__ - Running unseen_object_with_random_light_condition validation...
cc_projection/diffusion_pytorch_model.safetensors not found
The config attributes {'cc_projection': ['pipeline_zero1to3', 'CCProjection']} were passed to Neural_Gaffer_StableDiffusionPipeline, but are not expected and will be ignored. Please verify your model_index.json configuration file.
Keyword arguments {'cc_projection': ['pipeline_zero1to3', 'CCProjection']} are not expected by Neural_Gaffer_StableDiffusionPipeline and will be ignored.
0it [00:04, ?it/s]
Traceback (most recent call last):
  File "/share/phoenix/nfs02/S6/localdisk/hj453/code/Neural_Gaffer/neural_gaffer_training.py", line 1262, in <module>
    main(args)
  File "/share/phoenix/nfs02/S6/localdisk/hj453/code/Neural_Gaffer/neural_gaffer_training.py", line 1104, in main
    image_logs, temp_log = log_validation(
  File "/share/phoenix/nfs02/S6/localdisk/hj453/code/Neural_Gaffer/neural_gaffer_training.py", line 143, in log_validation
    prediction_image_sample1_new = prediction_image_sample1.reshape((1,-1, w, 3)).squeeze()
NameError: name 'prediction_image_sample1' is not defined
[rank0]: Traceback (most recent call last):
[rank0]:   File "/share/phoenix/nfs02/S6/localdisk/hj453/code/Neural_Gaffer/neural_gaffer_training.py", line 1262, in <module>
[rank0]:     main(args)
[rank0]:   File "/share/phoenix/nfs02/S6/localdisk/hj453/code/Neural_Gaffer/neural_gaffer_training.py", line 1104, in main
[rank0]:     image_logs, temp_log = log_validation(
[rank0]:   File "/share/phoenix/nfs02/S6/localdisk/hj453/code/Neural_Gaffer/neural_gaffer_training.py", line 143, in log_validation
[rank0]:     prediction_image_sample1_new = prediction_image_sample1.reshape((1,-1, w, 3)).squeeze()
[rank0]: NameError: name 'prediction_image_sample1' is not defined
